description: Building Wealth - Protecting Legacies

hb:
  logo: 'images/GoldLeafLogo.jpg'
  header:
    brand: " " # the brand name, leave it empty to use site's title.
    breakpoint: lg
    full_width: true
    menus_allignment: center
    logo_bg: white # logo background color, used by logo with transparent background.
    socials:
      github: WealthInnovationsCA
      # linkedin: foo
      twitter: wealthinnovate
      # mastodon: foo
      facebook: Wealth-Innovations-Inc/61566323390992
      # instagram: foo

  footer:
    socials:
      gmail: 'mailto: info@WealthInnovations.ca'
      twitter: wealthinnovate
      facebook: Wealth-Innovations-Inc/61566323390992
    powered_by: false
  blog:
    paginate: 12 # paginate.
    home: # homepage settings.
      featured_posts: 5 # the number of the featured posts.
      main_sections: # leave it empty to include all regular pages.
 #       - docs
 #       - blog
 #       - tutorials
 #   giscus:
 #     repo: hbstack/theme
 #     repo_id: R_kgDOJP3qtA
 #     category_id: DIC_kwDOJP3qtM4CVavM
 # docs:
 #   giscus:
 #     repo: hbstack/theme
 #     repo_id: R_kgDOJP3qtA
 #     category_id: DIC_kwDOJP3qtM4CVavM
  content_panel:
    repo:
      service: github # github or gitlab.
      repo: WealthInnovationsCA/WealthInnovationsCA-Hugo
      branch: main
      # subpath: exampleSite

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: '/images/GoldLeafButton.png'
    # svg_icon: /image/favicon.svg # use logo as favicon.

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  debug: false
  manifest:
    background_color: white
    theme_color: green
    short_name: 'WealthInnovationsInc'

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
